version: "3.5"
services:
  pg:
    build:
      context: ./data
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "co2pop"
    ports:
        - "5432:5432"
    volumes:
        - "postgres_data:/var/lib/postgresql/data"
  api:
    container_name: "api"
    build: ./api/
    ports:
        - "3001:3001"
    depends_on:
      - pg
volumes:
  postgres_data: 
