version: "3.5"
networks:
  co2pop_dev: 
    name: co2pop_dev
services:
  co2pop_client:
    build:
      context: ./client
    command: "sh -c \"npm start\""
    container_name: co2pop_client
    depends_on:
      - co2pop_api
    networks:
      - co2pop_dev
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - "./client/src:/app/src"
      - "./client/package.json:/app/package.json"
      - "./client/package-lock.json:/app/package-lock.json"
  co2pop_api:
    container_name: co2pop_api
    build: ./api/
    depends_on:
      - co2pop_pg
    command: "sh -c \"./wait-for co2pop_pg:5432 -- npm start\""
    environment: 
      DB_HOST: co2pop_pg
      DB_USER: postgres
      DB_PASS: password
      DATABASE_URL: postgres://postgres:password@co2pop_pg:5432/co2pop
    networks:
      - co2pop_dev
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - "./api/src/:/app/src"
      - "./api/package.json:/app/package.json"
      - "./api/package-lock.json:/app/package-lock.json"
  co2pop_pg:
    build:
      context: ./data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: co2pop
    networks:
      - co2pop_dev
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres_data: 
