version: "3"
services:
  api:
    container_name: "api"
    build: ./api/
    ports:
      - "3001:3001"
  pg:
    image: "postgres:12"
    container_name: "postgres"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
        - "5432:5432"
    volumes:
        - ./pg/db_data:/var/lib/postgresql/data